export const PRODUCT_LIST_REQUEST = "PRODUCT_LIST_REQUEST";
export const PRODUCT_LIST_SUCCESS = "PRODUCT_LIST_SUCCESS";
export const PRODUCT_LIST_FAIL = "PRODUCT_LIST_FAIL";


export const PRODUCT_DETAILS_REQUEST = "PRODUCT_DETAILS_REQUEST";
export const PRODUCT_DETAILS_SUCCESS = "PRODUCT_DETAILS_SUCCESS";
export const PRODUCT_DETAILS_FAIL = "PRODUCT_DETAILS_FAIL";

export const ADD_ITEM_TO_CART = "ADD_ITEM_TO_CART";
export const SHIPPING_CART = "SHIPPING_CART";
export const CART_PAYMENT_METHOD = "CART_PAYMENT_METHOD";
export const REMOVE_CART_ITEM = "REMOVE_CART_ITEM";