export const PRODUCT_REQUEST = "PRODUCT_REQUEST"
export const PRODUCT_REQUEST_SUCCESS = "PRODUCT_REQUEST_SUCCESS"
export const PRODUCT_REQUEST_FAIL = "PRODUCT_REQUEST_FAIL"


export const PRODUCT_DETAILS_REQUEST = "PRODUCT_DETAILS_REQUEST";
export const PRODUCT_DETAILS_SUCCESS = "PRODUCT_DETAILS_SUCCESS";
export const PRODUCT_DETAILS_FAIL = "PRODUCT_DETAILS_FAIL";

export const ADD_CART_ITEM = "ADD_CART_ITEM";
export const REMOVE_CART_ITEM = "REMOVE_CART_ITEM";