const data ={
products :[
{
_id: 1,
 name:'T shirt',
category:'Shirts',
image:'/productImages/p1.jpg',
price:100,
countInStock:10,
brand:'Nike',
rating:'4.5',
numReviews: 11,
description:'High Quality Slim Shirts',

},
{_id: 2,
name:'Track suit',
category:'Shirts',
image:'/productImages/p2.jpg',
price:150,
countInStock:10,
brand:'Adidas',
rating:'4.5',
numReviews: 11,
description:'High Quality Slim Shirts',

},
{_id: 3,
name:'Canvass',
category:'Shoe',
image:'/productImages/p3.jpg',
price:100,
countInStock:10,
brand:'Nike',
rating:'4.5',
numReviews: 11,
description:'High Quality Slim Shoe',

},
{_id: 4,
name:'jackes',
category:'Shirts',
image:'/productImages/p4.jpg',
price:170,
countInStock:10,
brand:'Nike',
rating:'4.5',
numReviews: 11,
description:'High Quality Slim Shirts',

},
{_id: 5,
name:'Puma Jacket',
category:'Shirts',
image:'/productImages/p5.jpg',
price:200,
countInStock:10,
brand:'Nike',
rating:'4.5',
numReviews: 11,
description:'High Quality',

},
{_id: 6,
name:'Trouser',
category:'Trouser',
image:'/productImages/p6.jpg',
price:100,
countInStock:0,
brand:'Nike',
rating:'4.5',
numReviews: 11,
description:'High Quality Slim Shirts',

},
{_id: 7,
name:'Headphones',
category:'Shirts',
image:'/productImages/p7.jpg',
price:100,
countInStock:10,
brand:'Nike',
rating:'4.5',
numReviews: 11,
description:'High Quality Slim Shirts',

},
{_id: 8,
name:'Headphones',
category:'Shirts',
image:'/productImages/p8.jpg',
price:100,
countInStock:10,
brand:'Nike',
rating:'4.5',
numReviews: 11,
description:'High Quality Slim Shirts',

},
{_id: 9,
name:'Headphones',
category:'Shirts',
image:'/productImages/p9.jpg',
price:100,
countInStock:10,
brand:'Nike',
rating:'4.5',
numReviews: 11,
description:'High Quality Slim Shirts',

},
{_id: 10,
name:'Headphones',
category:'Shirts',
image:'/productImages/p10.jpg',
price:100,
countInStock:10,
brand:'Nike',
rating:'4.5',
numReviews: 11,
description:'High Quality Slim Shirts',

},
{_id: 11,
name:'Headphones',
category:'Shirts',
image:'/productImages/p11.jpg',
price:100,
countInStock:10,
brand:'Nike',
rating:'4.5',
numReviews: 11,
description:'High Quality Slim Shirts',

},
{_id: 12,
name:'Headphones',
category:'Shirts',
image:'/productImages/p12.jpg',
price:100,
countInStock:10,
brand:'Nike',
rating:'4.5',
numReviews: 11,
description:'High Quality Slim Shirts',

},

],


};
export default data;